apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incident-responder.fullname" . }}-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "incident-responder.backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
